python evalResult.py dev.out dev.prediction1
python evalResult.py dev.out dev.prediction2
python evalResult.py dev.out dev.prediction3_k_1
python evalResult.py dev.out dev.prediction3_k_2
python evalResult.py dev.out dev.prediction3_k_3
python evalResult.py dev.out dev.prediction3_k_4
python evalResult.py dev.out dev.prediction3_k_5
python evalResult.py dev.out dev.prediction3_k_6
python evalResult.py dev.out dev.prediction3_k_7
python evalResult.py dev.out dev.prediction3_k_8
python evalResult.py dev.out dev.prediction4